global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs-backend'
    metrics_path: /api/metrics
    file_sd_configs:
      - files:
          - '/etc/prometheus/sd/backend.json'
        refresh_interval: 1m
